name: Bug Report
description: File a bug report
title: "[Bug]:"
labels: [Bug]
assignees: 
  - Slok7565
  - QingFeng-awa
body:
  - type: checkboxes
    attributes:
      label: Prerequisites
      description: Thank you for taking the time to fill out this issue report! Before you begin, you will need to confirm the following.
      options:
        - label: I have searched for related issues in the [议题](https://github.com/XtremeWave/FinalSuspect) list.
          required: true
        - label: I am using the latest version of FinalSuspect.
          required: true
        - label: This is an issue with the FinalSuspect project itself. 
          required: true
  - type: markdown
    attributes:
      value: "## Details"
  - type: textarea
    attributes:
      label: "What happened?"
      description: "For ease of management, please do not report multiple unrelated issues under the same issue."
    validations:
      required: true
  - type: dropdown
    attributes:
      label: What is the frequency of recurrence for this issue?
      options:
        - The issue can be consistently reproduced.
        - The issue is reproducible, but the probability is not 100%.
        - The probability of this issue recurring depends on the user's device.
        - I don't know.
    validations:
      required: true
  - type: textarea
    attributes:
      label: "Reproduce Steps"
      description: "If it can be consistently reproduced, please provide detailed steps.<br>Even if it cannot be consistently reproduced, please still provide the steps of how you discovered it."
  - type: textarea
    attributes:
      label: "Relevant log output"
      description: "Please refer to [this document](https://www.xtreme.net.cn/docs/FS/en-us/Guide/OutputLog) to export FinalSuspect logs."
      render: shell
  - type: textarea
    attributes:
      label: "Additional information"
      description: "If you have other information to note, you can fill it in here."
