name: Check Asset Size

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  check_asset_size:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Find files larger than 25MB in Assets directory
        id: check-size
        run: |
          # 使用 null 字符分隔符处理含空格的文件名
          if find Assets -type f -size +25M -print0 | grep -qz .; then
            echo "Found files larger than 25MB in Assets directory:"
            
            # 使用 find -ls 直接获取文件大小（更可靠的跨系统兼容性）
            find Assets -type f -size +25M -ls | awk '
              BEGIN { OFS="\t" }
              {
                size=$7; 
                file=$11;
                for(i=12; i<=NF; i++) file=file" "$i;
                print size, file
              }
            ' | while IFS=$'\t' read -r size file; do
              echo "::error::- $file ($size)"
            done
            
            echo "large_files=true" >> $GITHUB_OUTPUT
          else
            echo "No files larger than 25MB found in Assets directory."
            echo "large_files=false" >> $GITHUB_OUTPUT
          fi

      - name: Fail if large files found
        if: steps.check-size.outputs.large_files == 'true'
        run: |
          echo "::error::Found one or more asset files larger than 25MB"
          exit 1
