name: Check Security.md Update

on:
  pull_request:
    types: [opened, synchronize, labeled, unlabeled, reopened]

jobs:
  check-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Check for 'Develop' label
        id: check-label
        run: |
          if jq --exit-status '.pull_request.labels[] | select(.name == "Develop")' "$GITHUB_EVENT_PATH" >/dev/null; then
            echo "has_develop_label=true" >> $GITHUB_OUTPUT
          else
            echo "has_develop_label=false" >> $GITHUB_OUTPUT
          fi

      - name: Skip if no 'Develop' label
        if: steps.check-label.outputs.has_develop_label == 'false'
        run: |
          echo "PR does not have 'Develop' label, skipping..."
          exit 0

      - name: Check SECURITY.md changes
        id: check-security
        run: |
          # 比较 PR 合并提交与其父节点（基础分支）的差异
          if git diff --name-only HEAD^1 HEAD | grep -q '^SECURITY.md$'; then
            echo "security_modified=true" >> $GITHUB_OUTPUT
          else
            echo "security_modified=false" >> $GITHUB_OUTPUT
          fi

      - name: Fail if SECURITY.md not modified
        if: steps.check-label.outputs.has_develop_label == 'true' && steps.check-security.outputs.security_modified == 'false'
        run: |
          echo "SECURITY.md file was not modified but PR has 'Develop' label"
          exit 1
